<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;
use AppBundle\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function listCommentsQuery(Post $post)
    {
        return $this->createQueryBuilder('c')
            ->Where('c.post = :post')
            ->andWhere('c.parent is null')
            ->setParameter('post', $post)
            ->orderBy('c.createDate', 'DESC')
            ->getQuery();
    }

    public function countReplies(Comment $parent)
    {
      return $this->createQueryBuilder('c')
          ->select('COUNT(c)')
          ->Where('c.parent = :parent')
          ->setParameter('parent', $parent)
          ->getQuery()->getSingleScalarResult();
    }
}
