<?php

namespace AppBundle\Repository;

/**
 * PostVoterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostVoterRepository extends \Doctrine\ORM\EntityRepository
{
}
