<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankRepository extends EntityRepository
{
  public function findUserRank($reputation)
  {
    $query = $this->createQueryBuilder('p')
      ->Where('p.minReputation <= :reputation')
      ->setParameter('reputation', $reputation)
      ->orderBy('p.id', 'DESC')
      ->getQuery();

    return $query->setMaxResults(1)->getOneOrNullResult();
  }
}
