<?php
namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * SearchActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchActivityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLast(User $user)
    {
        return $this->createQueryBuilder('sa')
            ->where('sa.user = :user')
            ->setParameter('user', $user)
            ->orderBy('sa.searchDate', 'ASC')
            ->getQuery()
            ->setMaxResults(1)
            ->getSingleResult();
    }
}
