imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    upload_directory: '%kernel.project_dir%/web/uploads'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: team@geekhub.com
        sender_name: GeekHub
    registration:
        form:
            type: AppBundle\Form\RegistrationType
        confirmation:
            enabled: true

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig'
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig'

ivory_ck_editor:
    configs:
        standard_config:
            toolbar: "standard_toolbar"
            extraPlugins: "codesnippet,widget,lineutils,widgetselection"
            skin: "moono-lisa,/ckeditor/skins/moono-lisa/"
    toolbars:
        configs:
            standard_toolbar: [["Cut", "Copy", "Paste", "PasteText", "PasteTextFromWord", "-", "Undo", "Redo"], ["Bold", "Italic",	"Underline", "Strike", "Subscript", "Superscript", "RemoveFormat"], ["NumberedList", "BulletedList", "Outdent", "Indent", 	"Blockquote"], ["Link", "Unlink", "Anchor"], ["Image", "Table", "HorizontalRule", "Smiley", "SpecialChar", "CodeSnippet"], "/", [	"Styles", "Format", "Font", "FontSize", "TextColor"]]
    plugins:
        codesnippet:
            path: "/ckeditor/plugins/codesnippet/"
            filename: "plugin.js"
        widget:
            path: "/ckeditor/plugins/widget/"
            filename: "plugin.js"
        lineutils:
            path: "/ckeditor/plugins/lineutils/"
            filename: "plugin.js"
        widgetselection:
            path: "/ckeditor/plugins/widgetselection/"
            filename: "plugin.js"

gos_web_socket:
    server:
        port: 8888
        host: 127.0.0.1
        router:
            resources:
                - Resources/config/routing.yml
